package gui;

import controller.Controller;
import model.Cliente;

import javax.swing.*;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;
import java.awt.*;
import java.math.BigDecimal;
import java.sql.SQLException;

/**
 * Pannello dell'interfaccia grafica riservato alla gestione del profilo cliente.
 * <p>
 * Permette la visualizzazione delle informazioni anagrafiche, del saldo attuale
 * e consente al cliente di effettuare ricariche del proprio credito.
 */
public class ClientePanel extends JPanel {

    private JPanel mainPanel;
    private JLabel lblNome;
    private JLabel lblEmail;
    private JLabel lblCredito;
    private JTextField txtRicarica;
    private JButton btnRicarica;
    private JPanel infoPanel;
    private JPanel ricaricaPanel;
    private JLabel lblImportoDesc;
    private final Controller controller;

    /**
     * Inizializza il pannello e registra un {@link AncestorListener} per
     * aggiornare automaticamente i dati ogni volta che il pannello viene visualizzato.
     *
     * @param controller il controller di sistema
     */
    public ClientePanel(Controller controller) {
        this.controller = controller;
        add(mainPanel);

        lblCredito.setFont(new Font("SansSerif", Font.BOLD, 14));
        btnRicarica.addActionListener(e -> ricaricaCredito());

        // Listener per ricaricare i dati quando il componente entra nello stage attivo
        this.addAncestorListener(new AncestorListener() {
            @Override
            public void ancestorAdded(AncestorEvent event) {
                aggiornaDati();
            }

            @Override
            public void ancestorRemoved(AncestorEvent event) {
            }

            @Override
            public void ancestorMoved(AncestorEvent event) {
            }
        });
    }

    /**
     * Recupera i dati aggiornati dal controller e refresha le label a schermo.
     */
    private void aggiornaDati() {
        try {
            if (controller.getUtenteLoggato() instanceof Cliente) {
                Cliente clienteSessione = (Cliente) controller.getUtenteLoggato();
                Cliente aggiornato = controller.getClienteById(clienteSessione.getIdUtente());

                lblNome.setText("Nome: " + aggiornato.getNome() + " " + aggiornato.getCognome());
                lblEmail.setText("Email: " + aggiornato.getEmail());
                lblCredito.setText("Credito Attuale: " + aggiornato.getCredito() + " €");
            }
        } catch (SQLException e) {
            System.err.println("Errore caricamento dati: " + e.getMessage());
        }
    }

    /**
     * Legge l'importo dal campo di testo e richiama la logica di ricarica nel controller.
     */
    private void ricaricaCredito() {
        try {
            String testo = txtRicarica.getText().replace(",", ".");
            if (testo.trim().isEmpty()) return;

            BigDecimal importo = new BigDecimal(testo);
            if (importo.compareTo(BigDecimal.ZERO) <= 0) {
                throw new IllegalArgumentException("L'importo deve essere maggiore di zero");
            }

            Cliente clienteSessione = (Cliente) controller.getUtenteLoggato();
            controller.ricaricaConto(clienteSessione.getIdUtente(), importo);
            JOptionPane.showMessageDialog(this, "Ricarica effettuata!");
            txtRicarica.setText("");
            aggiornaDati();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Errore: " + e.getMessage());
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        infoPanel = new JPanel();
        infoPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(10, 10, 10, 10), 5, 5));
        mainPanel.add(infoPanel, BorderLayout.NORTH);
        lblNome = new JLabel();
        lblNome.setText("Nome: ");
        infoPanel.add(lblNome, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblEmail = new JLabel();
        lblEmail.setText("Email: ");
        infoPanel.add(lblEmail, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblCredito = new JLabel();
        lblCredito.setText("Credito: ");
        infoPanel.add(lblCredito, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ricaricaPanel = new JPanel();
        ricaricaPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 10, 10));
        mainPanel.add(ricaricaPanel, BorderLayout.SOUTH);
        lblImportoDesc = new JLabel();
        lblImportoDesc.setText("Importo:");
        ricaricaPanel.add(lblImportoDesc);
        txtRicarica = new JTextField();
        txtRicarica.setColumns(10);
        ricaricaPanel.add(txtRicarica);
        btnRicarica = new JButton();
        btnRicarica.setText("Ricarica");
        ricaricaPanel.add(btnRicarica);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}