package gui;

import controller.Controller;
import model.Utente;

import javax.swing.*;
import java.awt.*;
import java.sql.SQLException;

/**
 * Finestra principale dell'applicazione che funge da Dashboard per l'utente autenticato.
 * <p>
 * Gestisce la visualizzazione dinamica dei tab di navigazione in base al ruolo
 * dell'utente (Cliente vs Operatore) e fornisce le funzionalità di logout e gestione sessione.
 */
public class DashboardFrame extends JFrame {

    private JPanel mainPanel;
    private JPanel headerPanel;
    private JLabel lblUserInfo;
    private JButton btnLogout;
    private JTabbedPane tabbedPane;

    private final Controller controller;

    /**
     * Crea il frame della dashboard e inizializza la struttura dei tab.
     *
     * @param controller il controller di sistema per la logica di business
     * @throws SQLException in caso di errori durante il caricamento iniziale dei dati
     */
    public DashboardFrame(Controller controller) throws SQLException {
        this.controller = controller;

        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setContentPane(mainPanel);
        setSize(1100, 750);
        setLocationRelativeTo(null);

        initDashboard();

        btnLogout.addActionListener(e -> {
            controller.logout();
            dispose();
            LoginFrame loginFrame = new LoginFrame(controller);
            loginFrame.setLocationRelativeTo(null);
            loginFrame.setVisible(true);
        });
    }

    /**
     * Configura l'interfaccia utente popolando il {@link JTabbedPane} con i pannelli
     * specifici per il ruolo dell'utente (Operatore o Cliente).
     *
     * @throws SQLException se si verifica un errore durante il recupero delle informazioni utente
     */
    private void initDashboard() throws SQLException {
        Utente utente = controller.getUtenteLoggato();
        if (utente != null) {
            String tipoUtente = controller.isOperatoreLoggato() ? "Operatore" : "Cliente";
            setTitle("Noleggio Auto - " + utente.getNome() + " " + utente.getCognome() + " (" + tipoUtente + ")");
            lblUserInfo.setText("Utente: " + utente.getUsername() + " [" + utente.getClass().getSimpleName() + "]");
        }

        tabbedPane.removeAll();

        // Logica di autorizzazione: definisce quali tab mostrare in base al ruolo
        if (controller.isOperatoreLoggato()) {
            tabbedPane.addTab("Gestione Parco Auto", new AutoPanel(controller));
            tabbedPane.addTab("Prenotazioni", new PrenotazionePanel(controller));
            tabbedPane.addTab("Noleggi Attivi", new NoleggioPanel(controller));
        } else {
            tabbedPane.addTab("Catalogo Auto", new AutoPanel(controller));
            tabbedPane.addTab("Le mie Prenotazioni", new PrenotazionePanel(controller));
            tabbedPane.addTab("I miei Pagamenti", new PagamentoPanel(controller));
            tabbedPane.addTab("Il mio Profilo", new ClientePanel(controller));
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        headerPanel = new JPanel();
        headerPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(10, 10, 10, 10), 10, 0));
        mainPanel.add(headerPanel, BorderLayout.NORTH);
        lblUserInfo = new JLabel();
        lblUserInfo.setText("Utente: ");
        headerPanel.add(lblUserInfo, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnLogout = new JButton();
        btnLogout.setText("Logout");
        headerPanel.add(btnLogout, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tabbedPane = new JTabbedPane();
        mainPanel.add(tabbedPane, BorderLayout.WEST);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}