package gui;

import controller.Controller;
import model.Noleggio;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.SQLException;
import java.util.List;

public class NoleggioPanel extends JPanel {
    private JPanel mainPanel;
    private JTable tabellaNoleggi;
    private JButton btnAggiorna;
    private JButton btnChiudi;

    private DefaultTableModel model;
    private final Controller controller;

    public NoleggioPanel(Controller controller) throws SQLException {
        this.controller = controller;

        add(mainPanel);

        model = new DefaultTableModel(new String[]{"ID", "Cliente", "Auto", "Stato"}, 0);
        tabellaNoleggi.setModel(model);

        btnAggiorna.addActionListener(e -> {
            try {
                caricaNoleggi();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Errore aggiornamento: " + ex.getMessage());
            }
        });

        btnChiudi.addActionListener(e -> {
            try {
                chiudiNoleggio();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Errore: " + ex.getMessage());
            }
        });

        caricaNoleggi();
    }

    private void caricaNoleggi() throws SQLException {
        model.setRowCount(0);
        List<Noleggio> lista = controller.getNoleggiAttivi();
        for (Noleggio n : lista) {
            model.addRow(new Object[]{
                    n.getIdNoleggio(),
                    n.getPrenotazione().getCliente().getNome() + " " + n.getPrenotazione().getCliente().getCognome(),
                    n.getPrenotazione().getAuto().getModello(),
                    "ATTIVO"
            });
        }
    }

    private void chiudiNoleggio() throws Exception {
        int row = tabellaNoleggi.getSelectedRow();
        if (row != -1) {
            int idNoleggio = (int) model.getValueAt(row, 0);
            controller.terminaNoleggio(idNoleggio);
            JOptionPane.showMessageDialog(this, "Noleggio terminato correttamente.");
            caricaNoleggi();
        } else {
            JOptionPane.showMessageDialog(this, "Seleziona un noleggio dalla tabella.");
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        final JScrollPane scrollPane1 = new JScrollPane();
        mainPanel.add(scrollPane1, BorderLayout.CENTER);
        tabellaNoleggi = new JTable();
        scrollPane1.setViewportView(tabellaNoleggi);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        mainPanel.add(panel1, BorderLayout.SOUTH);
        btnAggiorna = new JButton();
        btnAggiorna.setText("Aggiorna");
        panel1.add(btnAggiorna);
        btnChiudi = new JButton();
        btnChiudi.setText("Chiudi Noleggio");
        panel1.add(btnChiudi);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}