package gui;

import controller.Controller;
import model.Auto;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.sql.SQLException;
import java.util.List;
import java.util.Locale;

/**
 * Pannello dell'interfaccia grafica dedicato agli operatori.
 * <p>
 * Offre strumenti per monitorare il parco auto e modificarne lo stato operativo
 * (es. invio in manutenzione o ripristino della disponibilità).
 */
public class OperatorePanel extends JPanel {

    private JPanel mainPanel;
    private JLabel lblTitolo;
    private JTable tabellaAuto;
    private JScrollPane scrollPane;
    private JPanel azioniPanel;
    private JButton btnManutenzione;
    private JButton btnDisponibile;
    private JButton btnAggiorna;

    private DefaultTableModel tableModel;
    private final Controller controller;

    /**
     * Inizializza il pannello e configura la tabella di visualizzazione auto.
     *
     * @param controller il controller di sistema per gestire le operazioni sulle auto
     */
    public OperatorePanel(Controller controller) {
        this.controller = controller;

        add(mainPanel);

        String[] colonne = {"ID", "Targa", "Modello", "Stato", "Costo Giornaliero"};
        tableModel = new DefaultTableModel(colonne, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tabellaAuto.setModel(tableModel);
        tabellaAuto.getTableHeader().setReorderingAllowed(false);

        btnAggiorna.addActionListener(e -> caricaDati());
        btnManutenzione.addActionListener(e -> cambiaStato(Auto.StatoAuto.IN_MANUTENZIONE));
        btnDisponibile.addActionListener(e -> cambiaStato(Auto.StatoAuto.DISPONIBILE));

        caricaDati();
    }

    /**
     * Aggiorna la tabella recuperando l'elenco completo delle auto dal controller.
     */
    private void caricaDati() {
        try {
            tableModel.setRowCount(0);
            List<Auto> autoList = controller.getTutteAuto();

            for (Auto a : autoList) {
                tableModel.addRow(new Object[]{
                        a.getIdAuto(),
                        a.getTarga(),
                        a.getModello(),
                        a.getStato(),
                        a.getCostoDaily()
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Errore caricamento auto: " + e.getMessage(),
                    "Errore",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Modifica lo stato dell'auto selezionata nella tabella.
     *
     * @param nuovoStato lo stato {@link Auto.StatoAuto} da applicare
     */
    private void cambiaStato(Auto.StatoAuto nuovoStato) {
        int riga = tabellaAuto.getSelectedRow();

        if (riga == -1) {
            JOptionPane.showMessageDialog(this, "Seleziona un'auto dalla tabella", "Attenzione", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idAuto = (int) tableModel.getValueAt(riga, 0);

        try {
            controller.cambiaStatoAuto(idAuto, nuovoStato);
            JOptionPane.showMessageDialog(this, "Stato aggiornato con successo!", "Operazione Completata", JOptionPane.INFORMATION_MESSAGE);
            caricaDati();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Errore aggiornamento: " + e.getMessage(),
                    "Errore",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(10, 10, 10, 10), -1, -1));
        lblTitolo = new JLabel();
        Font lblTitoloFont = this.$$$getFont$$$("Arial", Font.BOLD, 16, lblTitolo.getFont());
        if (lblTitoloFont != null) lblTitolo.setFont(lblTitoloFont);
        lblTitolo.setText("Pannello Operatore - Gestione Auto");
        mainPanel.add(lblTitolo, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        scrollPane = new JScrollPane();
        mainPanel.add(scrollPane, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        tabellaAuto = new JTable();
        scrollPane.setViewportView(tabellaAuto);
        azioniPanel = new JPanel();
        azioniPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        mainPanel.add(azioniPanel, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        btnManutenzione = new JButton();
        btnManutenzione.setText("Manutenzione");
        azioniPanel.add(btnManutenzione);
        btnDisponibile = new JButton();
        btnDisponibile.setText("Disponibile");
        azioniPanel.add(btnDisponibile);
        btnAggiorna = new JButton();
        btnAggiorna.setText("Aggiorna");
        azioniPanel.add(btnAggiorna);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}