package gui;

import controller.Controller;
import model.Pagamento;
import javax.swing.*;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;

public class PagamentoPanel extends JPanel {
    private JPanel mainPanel;
    private JTable tablePagamenti;
    private JButton btnPaga;
    private DefaultTableModel model;
    private final Controller controller;

    public PagamentoPanel(Controller controller) {
        this.controller = controller;
        add(mainPanel);

        String[] colonne = {"ID", "Importo", "Stato"};
        model = new DefaultTableModel(colonne, 0);
        tablePagamenti.setModel(model);

        btnPaga.addActionListener(e -> pagaSelezionato());

        this.addAncestorListener(new AncestorListener() {
            @Override
            public void ancestorAdded(AncestorEvent event) {
                caricaPagamenti();
            }

            @Override
            public void ancestorRemoved(AncestorEvent event) {
            }

            @Override
            public void ancestorMoved(AncestorEvent event) {
            }
        });
    }

    private void pagaSelezionato() {
        int row = tablePagamenti.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Seleziona un pagamento in sospeso.");
            return;
        }

        int idPagamento = (int) model.getValueAt(row, 0);
        try {
            controller.confermaPagamento(idPagamento);
            JOptionPane.showMessageDialog(this, "Pagamento effettuato con successo!");
            caricaPagamenti();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Errore: " + ex.getMessage());
        }
    }

    private void caricaPagamenti() {
        try {
            model.setRowCount(0);
            int idCliente = controller.getUtenteLoggato().getIdUtente();
            List<Pagamento> pagamenti = controller.getPagamentiByCliente(idCliente);

            for (Pagamento p : pagamenti) {
                model.addRow(new Object[]{
                        p.getIdPagamento(),
                        p.getImporto() + " €",
                        p.getStato()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Errore caricamento pagamenti: " + e.getMessage());
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        final JScrollPane scrollPane1 = new JScrollPane();
        mainPanel.add(scrollPane1, BorderLayout.CENTER);
        tablePagamenti = new JTable();
        scrollPane1.setViewportView(tablePagamenti);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        mainPanel.add(panel1, BorderLayout.SOUTH);
        btnPaga = new JButton();
        btnPaga.setText("Paga Selezionato");
        panel1.add(btnPaga);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}