package gui;

import controller.Controller;
import model.Cliente;
import model.Prenotazione;
import javax.swing.*;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.SQLException;
import java.util.List;

public class PrenotazionePanel extends JPanel {
    private JPanel mainPanel;
    private JTable tabella;
    private JButton btnConferma;
    private DefaultTableModel tableModel;
    private final Controller controller;

    public PrenotazionePanel(Controller controller) {
        this.controller = controller;
        add(mainPanel);

        btnConferma.setVisible(controller.isOperatoreLoggato());
        btnConferma.addActionListener(e -> {
            try {
                conferma();
            } catch (Exception ex) {
                throw new RuntimeException(ex);
            }
        });

        tableModel = new DefaultTableModel(new String[]{"ID", "Data Inizio", "Data Fine", "Stato", "Auto"}, 0);
        tabella.setModel(tableModel);

        this.addAncestorListener(new AncestorListener() {
            @Override
            public void ancestorAdded(AncestorEvent event) {
                try {
                    caricaDati();
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }

            @Override
            public void ancestorRemoved(AncestorEvent event) {
            }

            @Override
            public void ancestorMoved(AncestorEvent event) {
            }
        });
    }

    private void conferma() throws Exception {
        int row = tabella.getSelectedRow();
        if (row == -1) return;
        int id = (int) tableModel.getValueAt(row, 0);
        controller.confermaPrenotazione(id);
        caricaDati();
    }

    private void caricaDati() throws SQLException {
        tableModel.setRowCount(0);
        List<Prenotazione> lista = controller.isOperatoreLoggato() ?
                controller.getTuttePrenotazioni() :
                controller.getPrenotazioniCliente(controller.getUtenteLoggato().getIdUtente());
        for (Prenotazione p : lista) {
            tableModel.addRow(new Object[]{p.getIdPrenotazione(), p.getDataInizio(), p.getDataFine(), p.getStato(), p.getAuto().getModello()});
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        final JScrollPane scrollPane1 = new JScrollPane();
        mainPanel.add(scrollPane1, BorderLayout.CENTER);
        tabella = new JTable();
        scrollPane1.setViewportView(tabella);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}